server:
  port: 8888
  timeZone: UTC

spring:
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Artemiy7/config-server
#        native: file:///home/a1/IdeaProjects/config-server/src/main/resources/config
